language: python
python:
- 2.7
- 3.2
- 3.3
- pypy
install:
- pip install -r requirements.txt
script:
- pep8 .
- nosetests --with-coverage --cover-package=modlib
after_success:
- coveralls
notifications:
  email: false
  irc:
    channels:
    - secure: dPK8H6QMxzTQ58oBems1Wbk/C2ciWD3mq+9lLDOfsk4yJgFtyF9jDYQCg/AVlkt284uo28kh2h7lRct5wqjF7aeUMLbaosJByUeQasovFXPnatIPnRNDofkalRYgK2bpLnEN4kgiXsPqm0O4Bi4ONwCKwqcA8j+8w9f4aIUoEPg=
    template:
    - "%{repository}/%{branch}/%{build_number}: %{message} -- %{build_url}"
